# Generated by Django 5.1.4 on 2024-12-20 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "to_do_list",
            "0002_task_category_task_due_date_alter_task_description_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="category",
        ),
        migrations.RemoveField(
            model_name="task",
            name="due_date",
        ),
    ]
