# Generated by Django 5.1.3 on 2024-12-09 05:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload_notes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="noteimage",
            name="title",
        ),
        migrations.AddField(
            model_name="noteimage",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="noteimage",
            name="subject",
            field=models.CharField(
                choices=[
                    ("math", "Math"),
                    ("science", "Science"),
                    ("history", "History"),
                    ("english", "English"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="noteimage",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="noteimage",
            name="image",
            field=models.ImageField(upload_to="notes/images/"),
        ),
    ]
